# Generated by Django 4.1.7 on 2023-04-23 09:31

import about.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='citizenship_back',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='citizenship_front',
        ),
        migrations.AddField(
            model_name='vendor',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to=about.models.upload_profile_picture),
        ),
        migrations.AddField(
            model_name='vendor',
            name='status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Block', 'Block')], max_length=255, null=True),
        ),
    ]
