# Generated by Django 4.1.7 on 2023-04-23 09:41

import about.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_remove_vendor_citizenship_back_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='profile',
        ),
        migrations.AlterField(
            model_name='vendor',
            name='phone',
            field=models.IntegerField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=about.models.upload_profile_picture),
        ),
    ]
