# Generated by Django 4.1.7 on 2023-04-23 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_alter_vendor_license_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
