# Generated by Django 4.1.7 on 2023-04-24 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_alter_vendor_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='datar',
            name='volume',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
