# Generated by Django 4.1.7 on 2023-05-17 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0008_alter_vendor_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='dustbin',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='notification_type',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='status',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.AddField(
            model_name='notification',
            name='data_entry',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='about.datar'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
